/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.tedneward.minicalc

import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertEquals
import org.antlr.v4.runtime.ANTLRInputStream
import org.antlr.v4.runtime.Token
import java.io.FileInputStream
import java.io.StringReader
import java.util.LinkedList


class MiniCalcParserTests {
}
